### ISSUE TITLE
FRONT APP - Recherche

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-frontapp#1]
Sur le frontapp, sur quels champs (ou autres critères) sont basées les recherches parmi les publications ?

**Comment by clemoigno** [comment]
@lvinsonneau 
Numéro de l'acte et type de l'acte.
Recherche en mode 'contient', case insensitive.

**Comment by lvinsonneau** [comment]
@clemoigno : il n'y a pas l'objet de l'acte ?

**Comment by clemoigno** [comment]
Au temps pour moi mes doigts ont rippé, c'est numéro + objet (et pas type)

**Comment by lvinsonneau** [comment]
pas de souci, merci @clemoigno

**Comment by ElodieTessier** [comment]
Bonjour,
Depuis la refonte de la marque blanche et la MEP de janvier dernier, pouvez vous re-spécifier la recherche svp ?
La recherche est elle toujours sur le mode 'contient', case insensitive ?
J'ai un utilisateur qui me demande si les mots clés s'ajoutent avec un **et** ou avec un **ou** ?

Merci à vous,

**Comment by yguenneugues** [comment]
Bonjour,
La recherche de l'outil de publication n'a pas été modifié

**Comment by lvinsonneau** [comment]
@yguenneugues : pour bien répondre à la question de notre utilisateur, quand tu cumules 2 mots clés, c'est un **ET** ou un **OU** (ou autre chose) qui est appliqué dans le cadre de la recherche ?

**Comment by yguenneugues** [comment]
Je vois que j'ai affaire à des amateurs d'algèbre de Boole  :)

Il s'agit d'une requête SQL en mode contient (case insensitive) sur deux champs: 
- numero_de_lacte
- objet

On recherche dans la Base de donnée si on trouve une publication qui contient le texte tapé par l'utilisateur dans la colonne 
numero_de_lacte **ou** objet.
si on tape "toto titi" on retournera les publications que contiennent "toto titi" dans le numéro de l'acte ou bien dans l'objet.

Voila le code 
```
 searchFilter = "%{}%".format(filter)
  result = Publication.query.filter(
                    or_(Publication.numero_de_lacte.like(searchFilter), Publication.objet.like(searchFilter)),
                    Publication.siren == siren, Publication.est_supprime == est_supprime).order_by(
                    sortField).paginate(int(args['pageIndex']) + 1, per_page=int(args['pageSize']))
```

Le code ce trouve ici : https://github.com/megalis-bretagne/opendata-extraction/blob/master/app/controller/PublicationCtrl.py
fonction /search

**Exemple**: Je recherche le mot TEST
je trouve les publications qui ont test dans le numéro de l'acte ou bien dans le l'objet de l'acte

![image](https://user-images.githubusercontent.com/10934427/225068212-ed255b06-689c-4a47-8dc2-7f2611466367.png)

**Comment by lvinsonneau** [comment]
Merci @yguenneugues,  suis démasquée (sur ma passion concernant l'algèbre de Boole...) ;-)...
Donc si je résume : c'est un **ET** pour le cumul des 2 mots recherchés (recherche la chaîne de caractères titi **ET**toto), et c'est un **OU** pour les champs dans lesquels il recherche (numéro_de_lacte **OU** objet)
J'ai bon ?

**Comment by yguenneugues** [comment]
On recherche la chaine complète "toto titi" ( avec l'espace)
On ne trouvera pas la publication avec comme numéro d'acte "tototiti" (sans espace entre les deux)

sinon oui tu as bon

**Comment by lvinsonneau** [comment]
Merci @yguenneugues , c'est très clair maintenant !
