### ISSUE TITLE
Pré-production : Visualisation des publications impossible, message erreur : 

### ISSUE THREAD

**Issue by Cridard** [megalis-bretagne/opendata-frontapp#10]
Bonjour,
il n'est plus possible de visionner les publications : 
"Erreur Impossible de récupérer les publications à valider Réessayer "?
Peut-être est-ce lié au nouveau flux publication sans TdT qui serait incorrectement formaté, manque d'infos...?
J'ai cette erreur en étant connecté sur https://data-publication-preprod.megalis.bretagne.bzh/?etat= avec mon compte SA.

**Comment by Cridard** [comment]
ça fonctionne à nouveau, peut-être des actions effectuées de votre côté ? (après vérif, pb non lié au nouveau flux)

**Comment by yguenneugues** [comment]
@Cridard Je confirme, ça venait d'un déploiement KO en preprod
