### ISSUE TITLE
Mise à niveau du module d'admin pour la création des connecteurs et associations OPENDATA GED

### ISSUE THREAD

**Issue by Cridard** [megalis-bretagne/opendata-frontapp#13]
Bonjour,

serait-il possible de faire évoluer l'outil d'admin (https://data-publication.megalis.bretagne.bzh/pastell)  de création des connecteurs et associations OPENDATA.
Actuellement il n'intègre pas la création des connecteurs/assos pour les types de dossier :  
- documents-budgetaires-studio
- autres-studio-sans-tdt

**Comment by spelhate** [comment]
En complément, je souligne que la priorité va sur la création et l'association du connecteur **documents-budgetaires-studio** puisque le connecteur **autres-studio-sans-tdt** est géré indépendamment et de façon automatique.

**Comment by Cridard** [comment]
exemple en pré-produtcion, création d'une nouvelle entité ce jour le 05/04/23 : https://pastell-preprod.megalis.bretagne.bzh/Flux/index?id_e=3826
et exécution du module d'admin de création des connecteurs : résultat : 
création de 3 connecteurs GED  
![image](https://user-images.githubusercontent.com/97181939/230021922-6cd78ec0-489c-4659-a2fc-550768fb4180.png)

et associations sur les dossiers  : 
actes-generique                      => ged-megalis-opendata-auto-AG
arretes-individuels-studio     =>ged-megalis-opendata-auto
actes-reglementaires-studio  =>ged-megalis-opendata-auto
autres-studio                           =>ged-megalis-opendata-auto
deliberations-studio               => ged-megalis-opendata-auto

il faudrait en plus associer les dossiers : 
- actes-automatique
- documents-budgetaires-studio
- autres-studio-sans-tdt   (moins prioritaire)

**Comment by lvinsonneau** [comment]
vu en point suivi de projet : demande obsolète
en revanche supprimer les écrans correspondants dans les paramétrages Pastell

**Comment by syji35** [comment]
Correction OK en preprod

**Comment by lvinsonneau** [comment]
demande obsolète
