### ISSUE TITLE
Iframe marque blanche actes - Préconisations pour que le volet de visualisation s'ouvre bien sur le site internet des communes

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/opendata-frontapp#14]
Bonjour,
Pour faire suite à la préconisation d’Emmanuel Guevel : "le volet est affiché si l'iframe est plus large que 960 pixels"
Pouvez-vous modifier l'iframe actuelle pour intégrer cette préconisation svp ?

**Comment by yguenneugues** [comment]
Préconisation à donner aux organismes qui intègre l'iframe

**Comment by ElodieTessier** [comment]
3 raisons à ma demande : 
- Éviter des tickets et interventions auprès des collectivités
- J'imagine que ce n'est pas propre à Mégalis mais valable pour tous les ré/utilisateurs
- Mettre en cohérence avec le Mviewer "services" que nous avons mis à jour
https://geobretagne.fr/mviewer/?config=/apps/megalis-services/config.xml#
![image](https://user-images.githubusercontent.com/97222408/233414412-daeae14e-1692-4bea-b568-f965c424a2fc.png)

**Comment by yguenneugues** [comment]
height c'est la hauteur.
La recommandation d’Emmanuel concerne la largeur. Actuellement l'iframe prend l'ensemble de la place disponible. Si vous voulez voir le volet de lecture pdf il faut prévoir un minimum 960px pour que celui s'affiche.
On ne peut rien faire au niveau du code de l'iframe

**Comment by ElodieTessier** [comment]
OK merci pour ces explications.
