### ISSUE TITLE
Ajouter un paramètrage de la couleur en code hexadécimal #RRGGBB

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/opendata-frontapp#15]
Une demande de la commune de Parigné qui regrette qu'un paramétrage en code hexadécimal #RRGGBB ne soit pas disponible pour que la marque blanche s'insère encore mieux dans un site internet.

<img width="388" alt="2023-11-27 17_25_45-Publication opendata" src="https://github.com/megalis-bretagne/opendata-frontapp/assets/97222408/f21b4029-3502-491b-819e-ee0a26fa3af3">

https://parigne.fr/deliberations/

**Comment by lvinsonneau** [comment]
Il ne s'agit pas uniquement d'**UNE** couleur, mais d'un thème composé de **5 couleurs** : 

- background, 
- background-clair, 
- background-2, 
- couleur primaire, 
- lien

Donc pas possible de choisir son code hexadécimal, en revanche s'il y a une proposition de nouveau thème avec l'envoi des 5 codes hexadécimaux + nom du theme), nous pourrons l'intégrer au code.

On peut voir les thèmes existants ici : https://github.com/megalis-bretagne/mq-actes/blob/master/src/styles/themes.scss

**Comment by lvinsonneau** [comment]
@ElodieTessier : je propose de clôturer le ticket, sauf à ce que tu aies des propositions à faire en provenance d'une collectivité ?

**Comment by ElodieTessier** [comment]
@lvinsonneau , je clôture l'issue.

**Comment by ElodieTessier** [comment]
Clôture de cette issue, faute d'une réponse ou d'autre demande allant dans ce sens.
