### ISSUE TITLE
FRONT-APP - Modifier objet de l'acte

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-frontapp#2]
Afin de se prémunir des questions autour de la conformité RGPD, une évolution fonctionnelle est demandée pour pouvoir modifier, a posteriori, l'objet d'un acte.
Cela permettrait de pouvoir corriger après coup des objets qui comporteraient des données nominatives (ex. "expulsion de M. Dupont"), sachant que l'objet de l'acte est une métadonnée systématiquement publiée sur data.gouv.fr (même si la délibération elle, ne l'est pas)

**Comment by clemoigno** [comment]
Evolution depuis l'interface d'administration des publications : permettre la modification de l'objet puis republication open data avec l'objet modifié.

**Comment by yguenneugues** [comment]
installé en preprod
![image](https://user-images.githubusercontent.com/10934427/165740541-b7bfce84-ae09-4be9-85e6-1c4f03c30a6e.png)

**Comment by lvinsonneau** [comment]
👍
