### ISSUE TITLE
Iframe marque blanche & referrer

### ISSUE THREAD

**Issue by spelhate** [megalis-bretagne/opendata-frontapp#4]
Actuellement il n'est pas possible de détecter dans les logs du serveur les sites web qui intègrent la marque blanche en **iframe** car cette info n'est pas envoyée par les navigateurs par défaut. Il est cependant possible de modifier le comportement par défaut des navigateurs en spécifiant correctement le paramètre **referrerpolicy** de la balise **iframe**
Je propose donc de modifier le code embarquable de la marque blanche en y ajoutant ce paramètre et en lui attribuant la valeur s**trict-origin-when-cross-origin**

```html
<iframe
   referrerpolicy="strict-origin-when-cross-origin" 
   style="border: 0;"
   src="https://data.megalis.bretagne.bzh/?siren=253514491"
   title="Marque blanche open data"
   width="100%"
   height="600">
</iframe>
```

Si le site de la mairie https://mairie.fr embarque en iframe   le fragment de code précédent, ce site laissera une trace sous la forme d'une signature referrer - `https://mairie.fr`  - dans les logs http du serveur hébergeant la marque blanche.

Si ok pour tout le monde, je propose une PR

**Comment by lvinsonneau** [comment]
@spelhate : on peut clore cette issue non ?
