### ISSUE TITLE
INTERFACE - Mise à jour des textes des différentes rubriques

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-frontapp#6]
Bonjour,

Suite à l'évolution au 1er juillet 2022 du périmètre de diffusion des actes, les textes des différents menus du front-app doivent évoluer.
En cliquant sur ce lien, vous verrez les propositions d'ancien et nouveaux textes : 
https://nextcloud.megalis.bretagne.bzh/s/2MB65aawF5MzWMg 

Merci de faire les modifications.

**Comment by yguenneugues** [comment]
installé en preprod

**Comment by lvinsonneau** [comment]
il manque un espace ici : 
![image](https://user-images.githubusercontent.com/2498403/196624499-0726cbbb-6ab7-4cf6-aae4-72369920e4a3.png)

**Comment by yguenneugues** [comment]
@lvinsonneau  corrigé en preprod

**Comment by lvinsonneau** [comment]
OK pour passage en prod.

**Comment by lvinsonneau** [comment]
MEP OK
